version: '3'

services:
  inception_mariadb:
    build: ./requirements/mariadb
    image: inception_mariadb:latest
    container_name: inception_mariadb
    restart: on-failure:10
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
    volumes:
      - ./requirements/mariadb/conf/my.conf:/etc/mysql/my.cnf:ro
      - inception_mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "if [ -e /tmp/healthcheck_disabled ]; then exit 0; else if mysqladmin ping -h localhost -uroot; then touch /tmp/healthcheck_disabled; exit 0; else exit 1; fi; fi"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
    networks:
      - inception_mariadb_net

  inception_wordpress:
    build: ./requirements/wordpress
    image: inception_wordpress:latest
    container_name: inception_wordpress
    restart: on-failure:5
    volumes:
      - inception_wp_data:/var/www/html
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_HOME: ${WP_HOME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_SUB_USER: ${WP_SUB_USER}
      WP_SUB_PASSWORD: ${WP_SUB_PASSWORD}
      WP_SUB_EMAIL: ${WP_SUB_EMAIL}
    depends_on:
      inception_mariadb:
        condition: service_healthy
    networks:
      - inception_mariadb_net
      - inception_wordpress_net

  inception_nginx:
    build: ./requirements/nginx
    image: inception_nginx:latest
    container_name: inception_nginx
    restart: on-failure:5
    volumes:
      - inception_wp_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - inception_wordpress
    networks:
      - inception_wordpress_net

volumes:
  inception_mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./hnoguchi/data/mariadb
  inception_wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./hnoguchi/data/wordpress

networks:
  inception_mariadb_net:
    driver: bridge
    internal: true
  inception_wordpress_net:
    driver: bridge
