version: '3'

# containers
services:
  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./requirements/mariadb/conf/my.conf:/etc/mysql/my.cnf:ro
      - ./requirements/mariadb/data:/var/lib/mysql

volumes:
  db_data:
