version: '3'

services:
  inception_mariadb:
    build: ./requirements/mariadb
    image: inception_mariadb:latest
    container_name: inception_mariadb
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
    volumes:
      - ./requirements/mariadb/conf/my.conf:/etc/mysql/my.cnf:ro
      - inception_mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_mariadb_net

  inception_wordpress:
    build: ./requirements/wordpress
    image: inception_wordpress:latest
    container_name: inception_wordpress
    restart: always
    volumes:
      - inception_wp_data:/var/www/html
    environment:
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_HOME: ${WP_HOME}
      WORDPRESS_TITLE: ${WP_TITLE}
      WORDPRESS_ADMIN_USER: ${WP_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    # expose:
    #   - "9000"
    depends_on:
      - inception_mariadb
    networks:
      - inception_mariadb_net
      - inception_wordpress_net

  inception_nginx:
    build: ./requirements/nginx
    image: inception_nginx:latest
    container_name: inception_nginx
    restart: on-failure:5
    volumes:
      # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - inception_wp_data:/var/www/html
    ports:
      - "443:443"
      # - "80:80"
    depends_on:
      - inception_wordpress
    networks:
      - inception_wordpress_net

volumes:
  inception_mariadb_data:
  inception_wp_data:

networks:
  inception_mariadb_net:
    internal: true
  inception_wordpress_net:

#   mariadb:
#     environment:
#       GUEST_USER: $(DB_GUEST_USER)
#       GUEST_USER_PASSWORD: $(DB_GUEST_PASSWORD)
#
#   phpmyadmin:
#     build: ./requirements/bonus/phpmyadmin
#     container_name: phpmyadmin
#     restart: on-failure:5
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: ${PMA_HOST_NAME}
#       PMA_ALLOW_NO_PASSWORD: false
#       PMA_USER: ${PMA_USER_NAME}
#       PMA_PASSWORD: ${DB_ROOT_PASSWORD}
#     depends_on:
#       - mariadb
#     networks:
#       - pmanetwork
