version: '3'

services:
  inception_mariadb:
    build: ./requirements/mariadb
    container_name: inception_mariadb
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: $(DB_NAME)
      MYSQL_USER: $(DB_USER)
      MYSQL_PASSWORD: $(DB_PASSWORD)
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - inception_mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_mariadb_net

  inception_wordpress:
    build: ./requirements/wordpress
    container_name: inception_wordpress
    depends_on:
      - inception_mariadb
    restart: on-failure:5
    volumes:
      - inception_wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: inception_mariadb:3306
      WORDPRESS_DB_USER: $(DB_USER)
      WORDPRESS_DB_PASSWORD: $(DB_PASSWORD)
      WORDPRESS_DB_NAME: $(DB_NAME)
    # expose:
    #   - "9000"
    networks:
      - inception_mariadb_net
      - inception_wordpress_net

  inception_nginx:
    build: ./requirements/nginx
    container_name: inception_nginx
    restart: on-failure:5
    volumes:
      # - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - inception_wp_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - inception_wordpress
    networks:
      - inception_wordpress_net

volumes:
  inception_mariadb_data:
  inception_wp_data:

networks:
  inception_mariadb_net:
    internal: true
  inception_wordpress_net:

  # mariadb:
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     GUEST_USER: $(DB_GUEST_USER)
  #     GUEST_USER_PASSWORD: $(DB_GUEST_PASSWORD)
  #   volumes:
  #     - ./requirements/mariadb/conf/my.conf:/etc/mysql/my.cnf:ro

      # phpmyadmin:
      #   build: ./requirements/bonus/phpmyadmin
      #   container_name: phpmyadmin
      #   restart: on-failure:5
      #   ports:
      #     - "8080:80"
      #   environment:
      #     PMA_HOST: ${PMA_HOST_NAME}
      #     PMA_ALLOW_NO_PASSWORD: false
      #     PMA_USER: ${PMA_USER_NAME}
      #     PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      #   depends_on:
      #     - mariadb
      #   networks:
      #     - pmanetwork
