FROM debian:latest

RUN apt update
RUN apt install -y vim wget unzip
RUN apt install -y nginx
RUN apt install -y php8.2-fpm php8.2-mysqli php8.2-gd php8.2-curl php8.2-xml php8.2-mbstring php8.2-zip
RUN apt install -y mariadb-server


# apt install -y nginx \
# apt install -y mariadb-server \
# apt install -y php-fpm php-mysql php-curl php-json php-cgi php-gd php-mbstring php-xml php-xmlrpc
# apt install -y wget
