FROM debian:latest

RUN apt update
# RUN apt install -y vim wget unzip
# RUN apt install -y nginx
# RUN apt install -y php7.4-fpm php7.4-mysqli php7.4-gd php7.4-curl php7.4-xml php7.4-mbstring php7.4-zip
# RUN apt install mariadb-server
