# 参考
# https://qiita.com/witchcraze/items/92afbd09f89382d9745e
version: '3'

services:
  db:
    image: mysql:8.0
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - "3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    restart: on-failure:5
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: wordpress
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    restart: on-failure:5
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wp_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_data:
